[package]
name = "pokemon-text-game"
version = "1.0.0"
authors = ["sn99 <siddharthn.099@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
serde = "1.0.77"
serde_json = "1.0.27"
serde_derive = "1.0.77"
rodio = "0.11.0"
